import {chromium,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import fs from 'node:fs/promises';
import {checkWiring} from './wiring-web-checks.mjs';
import {checkZoom} from './zoom-web-checks.mjs';
const base=process.env.BLACKWIRE_BASE_PATH||'/';
const url='http://127.0.0.1:5187'+base;
const server=spawn(process.execPath,['scripts/preview-web.mjs'],{stdio:'pipe',env:process.env,windowsHide:true});
let browser;
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',()=>reject(new Error('Preview server exited before startup')));});
 browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();
 const errors=[],failed=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push([r.status(),r.url()]);});page.on('request',r=>requests.push(r.url()));
 await page.goto(url);await expect(page.getByRole('heading',{name:/Board library/})).toBeVisible();
 await expect(page.locator('.page-meta').getByText('Browser',{exact:true})).toBeVisible();
 await page.waitForLoadState('networkidle');
 expect(requests.filter(u=>u.includes('/library/media/'))).toHaveLength(0);
 const initialBytes=await page.evaluate(()=>performance.getEntriesByType('resource').reduce((n,r)=>n+(r.decodedBodySize||0),0));
 expect(initialBytes).toBeLessThan(15*1024*1024);
 await fs.mkdir('data/qa/web',{recursive:true});await page.screenshot({path:'data/qa/web/browser-guide.png'});
 await page.getByRole('combobox',{name:'Search boards and references'}).fill('teensy-4.1');await page.keyboard.press('Escape');
 await expect(page.locator('.board-card')).toHaveCount(1);
 await page.getByRole('button',{name:'View Teensy 4.1 references',exact:true}).click();
 const dialog=page.getByRole('dialog');await expect.poll(()=>dialog.locator('.scaled-image img').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
 const boardLink=await dialog.getByRole('link',{name:'Board link'}).getAttribute('href');expect(boardLink).toContain(base+'index.html?board=');
 const downloadEvent=page.waitForEvent('download');await dialog.getByRole('button',{name:'Save original',exact:true}).click();await downloadEvent;
 await dialog.getByRole('button',{name:'Save board',exact:true}).click();await page.reload();
 await page.getByRole('button',{name:'Saved boards',exact:false}).click();await expect(page.locator('.board-card')).toHaveCount(1);
 await page.goto(boardLink);await expect(page.getByRole('dialog',{name:'Teensy 4.1 references'})).toBeVisible();
 const catalog=await page.evaluate(base=>fetch(base+'catalog.json').then(r=>r.json()),base);
 const pdfBoard=catalog.boards.find(b=>b.assets.some(a=>a.extension==='pdf')&&b.assets.some(a=>a.type==='pinout image'));
 await page.goto(url+'?board='+encodeURIComponent(pdfBoard.id));await expect(page.getByRole('dialog')).toBeVisible();
 await page.locator('.asset-item').filter({has:page.locator('small',{hasText:'PDF'})}).first().click();
 await expect(page.locator('canvas[data-rendered="true"]')).toBeVisible();
 await page.getByRole('button',{name:'Next page'}).click();await expect(page.getByRole('status')).toHaveText('Page 2 of 7');
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Power desk',exact:false}).first().click();
 await expect(page.getByRole('heading',{name:'Voltage & current reference'})).toBeVisible();
 await page.getByRole('button',{name:'About the guide',exact:true}).click();
 await page.getByText('Original application code — MIT',{exact:true}).click();
 await expect(page.locator('.license-notices pre').first()).toContainText('Copyright (c) 2026 Kal (Your Pal Kal) / Valleytech Solutions');
 await page.getByText('Original guide material — CC BY 4.0',{exact:true}).click();
 await expect(page.locator('.license-notices pre').nth(1)).toContainText('Creative Commons Attribution 4.0 International Public License');
 await checkWiring(page,url,catalog,expect);
 await checkZoom(page,url,catalog,expect);
 let embedURL=url;
 await page.route('**/embed-test',route=>route.fulfill({contentType:'text/html',body:`<h1>Store page integration test</h1><iframe title="BWM guide" src="${embedURL}" style="width:100%;height:900px" sandbox="allow-scripts allow-same-origin allow-downloads allow-popups allow-popups-to-escape-sandbox"></iframe>`}));
 await page.goto('http://127.0.0.1:5187/embed-test');const frame=page.frameLocator('iframe');
 await expect(frame.getByRole('heading',{name:/Board library/})).toBeVisible();await frame.getByRole('combobox',{name:'Search boards and references'}).fill('ESP32-C5');await expect(frame.locator('.board-card').first()).toBeVisible();
 // Local actions must work without allowing native form submission in the store iframe.
 embedURL=url+'?board='+encodeURIComponent(pdfBoard.id);await page.reload();
 await frame.locator('.asset-item').filter({has:frame.locator('small',{hasText:'PDF'})}).first().click();
 await expect(frame.locator('canvas[data-rendered="true"]')).toBeVisible();
 await frame.getByRole('spinbutton',{name:'PDF page number'}).fill('3');await frame.getByRole('button',{name:'Go',exact:true}).click();
 await expect(frame.getByRole('status')).toHaveText('Page 3 of 7');
 await frame.getByRole('spinbutton',{name:'PDF page number'}).fill('4');await frame.getByRole('spinbutton',{name:'PDF page number'}).press('Enter');
 await expect(frame.getByRole('status')).toHaveText('Page 4 of 7');
 await expect(frame.locator('canvas[data-rendered="true"][aria-label$="page 4"]')).toBeVisible();
 await frame.getByRole('button',{name:'Close board',exact:true}).click();
 await frame.getByRole('button',{name:'Power desk',exact:false}).first().click();await frame.getByRole('tab',{name:'My measurements',exact:false}).click();
 for(const method of ['click','enter']){
  await frame.getByRole('button',{name:'Record a measurement',exact:true}).click();
  const measurement=frame.getByRole('dialog',{name:'Record a measurement',exact:true});
  await measurement.getByRole('button',{name:'Save measurement',exact:true}).click();await expect(measurement).toBeVisible();
  await measurement.getByLabel('Board',{exact:true}).selectOption(pdfBoard.id);
  await measurement.getByLabel('PCB revision',{exact:true}).fill('Automated test fixture');
  await measurement.getByLabel('Power input point',{exact:true}).fill('Simulated test input');
  await measurement.getByLabel('Measured voltage',{exact:false}).fill('3.3');
  await measurement.getByLabel('Average current',{exact:false}).fill('100');
  await measurement.getByRole('textbox',{name:'Conditions / firmware / peripherals',exact:true}).fill('Automated sandbox test '+method);
  await measurement.getByRole('textbox',{name:'Conditions / firmware / peripherals',exact:true}).press('Enter');await expect(measurement).toBeVisible();
  await measurement.getByLabel('Instrument / measurement method',{exact:true}).fill('Simulated input; not a hardware measurement');
  if(method==='click')await measurement.getByRole('button',{name:'Save measurement',exact:true}).click();
  else await measurement.getByLabel('Instrument / measurement method',{exact:true}).press('Enter');
  await expect(measurement).toHaveCount(0);await expect(frame.locator('.measurement-list')).toContainText('Automated sandbox test '+method);
 }
 await page.goto(url);await page.setViewportSize({width:390,height:844});await expect(page.getByRole('heading',{name:/Board library/})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto(url+'?board='+encodeURIComponent(pdfBoard.id));
 const mobileDialog=page.getByRole('dialog');await expect(mobileDialog).toBeVisible();
 const titleBox=await mobileDialog.getByRole('heading',{level:2}).boundingBox();
 const addBox=await mobileDialog.getByRole('button',{name:'Add to breadboard',exact:true}).boundingBox();
 const closeBox=await mobileDialog.getByRole('button',{name:'Close board',exact:true}).boundingBox();
 expect(addBox.y).toBeGreaterThanOrEqual(titleBox.y+titleBox.height);
 expect(closeBox.x).toBeGreaterThanOrEqual(0);expect(closeBox.x+closeBox.width).toBeLessThanOrEqual(390);
 await mobileDialog.getByRole('button',{name:'Close board',exact:true}).click();await expect(mobileDialog).toHaveCount(0);
 expect(errors).toEqual([]);expect(failed).toEqual([]);
 const report={passed:true,base,initialDecodedBytes:initialBytes,references:catalog.stats.referenceEntries,checks:['subpath assets','on-demand originals','dash search','image rendering','original download','browser bookmarks','direct board links','PDF pages','power desk','sandboxed embed','sandboxed PDF page jump by click and Enter','sandboxed measurement validation and saving','mobile layout','production CSP']};
 await fs.writeFile('data/qa/web/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser?.close();server.kill();}
