const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=(items,tag='ul')=>`<${tag}>${items.map(s=>`<li>${esc(s)}</li>`).join('')}</${tag}>`;
const link=(url,label)=>`<a href="${esc(url)}">${esc(label)}</a>`;
const site='https://valleytech-black-wire-guide.pages.dev';
export function wiringHTML(g,catalog,base){
 const table=`<div class="directory-table" tabindex="0" aria-label="Connection reference"><table><thead><tr>${g.columns.map(s=>`<th scope="col">${esc(s)}</th>`).join('')}</tr></thead><tbody>${g.rows.map(row=>`<tr>${row.map((s,i)=>i?`<td>${esc(s)}</td>`:`<th scope="row">${esc(s)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 return `<p class="note"><b>Applies to:</b> ${esc(g.scope)}</p><h2>When to use it</h2><p>${esc(g.useWhen)}</p><h2>Why it works this way</h2><p>${esc(g.why)}</p><figure class="wiring-figure"><a href="${base}library/${esc(g.image.file)}"><img src="${base}library/${esc(g.image.file)}" alt="${esc(g.image.alt)}" loading="lazy"></a><figcaption>Original Black Wire connection diagram. ${link(base+'library/'+g.image.file,'Open / save SVG')}</figcaption></figure><h2>Connection reference</h2>${table}<h2>Make the connection</h2>${list(g.steps,'ol')}<h2>Check before powering</h2>${list(g.checks)}${g.relatedParts.length?`<h2>Matching module references</h2><ul>${g.relatedParts.map(id=>catalog.makerParts.find(p=>p.id===id)).filter(Boolean).map(p=>`<li>${link(base+'?tab=makers&part='+p.id,p.name+' — original images and datasheets')}</li>`).join('')}</ul>`:''}<h2>Sources & review</h2><p>${esc(g.review)}. Reviewed ${esc(g.revision)}.</p><ul>${g.sources.map(s=>`<li>${link(s.url,s.title)}<br><small>${esc(s.locator)} · checked ${esc(s.checked)}</small></li>`).join('')}</ul><p>${esc(g.rights)} ${link('https://creativecommons.org/licenses/by/4.0/','CC BY 4.0')}</p><details><summary>Diagram fingerprint</summary><code>${esc(g.image.hash)}</code></details><h2>Continue learning</h2><ul>${g.relatedGuides.map(id=>catalog.wiringGuides.find(x=>x.id===id)).map(x=>`<li>${link(base+'wiki/wiring/'+x.id+'/',x.name)}</li>`).join('')}</ul><p>${link(base+'?tab=wiring&guide='+g.id,'Open this guide in the app')} · ${link(base+'wiki/wiring/','All wiring guides')}</p>`;
}
export function wiringMarkdown(g,catalog){
 return `# ${g.name}\n\n${g.summary}\n\n**Applies to:** ${g.scope}\n\n## When to use it\n\n${g.useWhen}\n\n## Why it works this way\n\n${g.why}\n\n![${g.image.alt}](${site}/library/${g.image.file})\n\n[Open / save the original SVG](${site}/library/${g.image.file})\n\n## Connection reference\n\n| ${g.columns.join(' | ')} |\n| ${g.columns.map(()=>'---').join(' | ')} |\n${g.rows.map(row=>'| '+row.join(' | ')+' |').join('\n')}\n\n## Make the connection\n\n${g.steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\n## Check before powering\n\n${g.checks.map(s=>'- '+s).join('\n')}\n\n## Matching module references\n\n${g.relatedParts.map(id=>catalog.makerParts.find(p=>p.id===id)).filter(Boolean).map(p=>`- [${p.name}](${site}/?tab=makers&part=${p.id}) — original images and datasheets`).join('\n')||'This is a general interface guide; match your own hardware documentation.'}\n\n## Sources & review\n\n${g.review}. Reviewed ${g.revision}.\n\n${g.sources.map(s=>`- [${s.title}](${s.url}) — ${s.locator}; checked ${s.checked}`).join('\n')}\n\n${g.rights}\n\n[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) · SHA-256: \`${g.image.hash}\`\n\n[Open the interactive guide](${site}/?tab=wiring&guide=${g.id}) · [All wiring guides](Wiring.md)\n`;
}
