import React,{useState} from 'react';
import {Download,RefreshCw,HardDrive,CheckCircle} from 'lucide-react';
import './desktop-maintenance.css';
const bytes=n=>`${(n/1024**3).toFixed(2)} GiB`;
export default function DesktopMaintenance({status,refresh}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!status)return <p role="status">Checking this installation…</p>;
 const {library:l,update:u}=status;
 async function action(kind,value){setBusy(true);setError('');try{await window.blackwire[kind](value);await refresh();}catch{setError('Could not finish this action. Try again.');}finally{setBusy(false);}}
 const labels={idle:'Ready to check',checking:'Checking for updates…',current:'You have the latest release',available:`Version ${u.availableVersion} is available`,downloading:`Downloading update · ${Math.floor(u.percent)}%`,ready:`Version ${u.availableVersion} is ready`,installing:'Saving your workbench and restarting…',error:'Update needs attention',unsupported:'Updates require an installed Windows or Linux DEB release'};
 return <div className="desktop-maintenance"><header className="page-header"><span className="eyebrow">Your installation</span><h1>Updates & offline library</h1><p>Keep Black Wire current. Your saved boards, measurements and downloaded references stay on this computer.</p></header>
 <div className="maintenance-cards"><section><RefreshCw size={26}/><h2>Application updates</h2><p>Installed version <b>{u.version}</b></p><p role="status">{labels[u.phase]}</p>{u.phase==='downloading'&&<progress aria-label="Application update progress" max="100" value={u.percent}/>}{u.error&&<p role="alert">{u.error}</p>}
 <div className="backup-actions">{!['unsupported','downloading','installing','ready'].includes(u.phase)&&<button className="secondary-button" disabled={busy||u.phase==='checking'} onClick={()=>action('updateAction','check')}><RefreshCw size={16}/>Check for updates</button>}{u.phase==='available'&&<button className="primary-button" disabled={busy} onClick={()=>action('updateAction','download')}><Download size={16}/>Download update</button>}{u.phase==='ready'&&<button className="primary-button" disabled={busy} onClick={()=>action('updateAction','install')}>Restart & update</button>}</div><p className="muted">Updates install only when you choose Restart & update. On Linux DEB installations, your system may ask for administrator authentication. The offline library is retained.</p></section>
 <section><HardDrive size={26}/><h2>Offline reference library</h2><p>Collection {l.snapshot}</p><p role="status">{l.scanning?'Checking downloaded files…':l.complete?'All references are available offline':l.running?'Downloading verified references…':'Some originals still need an internet connection'}</p><progress aria-label="Offline library progress" max={l.totalBytes||1} value={l.bytes}/><p>{l.available.toLocaleString()} / {l.total.toLocaleString()} files · {bytes(l.bytes)} / {bytes(l.totalBytes)}</p>{l.error&&<p role="alert">{l.error}</p>}
 <div className="backup-actions">{l.complete?<span className="reviewed-label"><CheckCircle size={18}/>Ready for offline use</span>:<button className="primary-button" disabled={l.scanning||busy} onClick={()=>action('libraryAction',l.running?'pause':'download')}>{l.running?'Pause download':l.error?'Retry library download':'Download offline library'}</button>}</div><p className="muted">Search and previews are included with the app. Originals download as you open them, or download the entire library here before going offline. Pause or close the app at any time; completed files are retained and reused after updates. Internet access and sufficient disk space are required for missing files.</p></section></div>{error&&<p role="alert">{error}</p>}</div>;
}
