import {AdapterTool,BatteryTool,BudgetTool,NumericField,PowerBasics} from './PowerTools.jsx';
import HardwareLinks from './HardwareLinks.jsx';
import MakersView from './MakersView.jsx';
import WiringView from './WiringView.jsx';
import {searchMakerParts} from './maker-search.mjs';
import './makers.css';
import DevicesView from './DevicesView.jsx';
import LicenseNotices from './LicenseNotices.jsx';
import React,{useEffect,useMemo,useRef,useState,useDeferredValue} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ArrowUpRight,ArrowRight,ArrowLeft,Bookmark,BookOpen,Zap,Wifi,SlidersHorizontal,Grid2X2,List,ChevronDown,ChevronRight,X,Plus,Minus,RotateCw,Maximize2,Download,ExternalLink,FileText,Image as ImageIcon,Info,Check,AlertTriangle,FolderOpen,Battery,Calculator,Trash2,Upload,Settings2,FlaskConical,Command,Menu,Clock,Layers,ShieldCheck} from 'lucide-react';
import {normalize,searchBoards,validateMeasurement,validateBackup,validateSavedWorkbench} from './domain.mjs';
import './styles.css';
import './professional.css';
import './theme.css';
import './brand.css';
import {BrandMark,ThemeSwitch,Kicker} from './Theme.jsx';
import GlobalSearch from './GlobalSearch.jsx';
import ReferenceImage from './ReferenceImage.jsx';
import {version as appVersion} from '../package.json';
import PinReference,{CoverageSummary} from './PinReference.jsx';
import {orderedAssets} from './pin-coverage.mjs';
import {resolveBoardId,remapWorkbench} from './catalog-aliases.mjs';
import {webEdition,appAsset,libraryURL} from './runtime.mjs';
const PdfViewer=React.lazy(()=>import('./PdfViewer.jsx'));

const number=n=>new Intl.NumberFormat('en-US').format(n);
const collectionId=edition=>String(edition||'').match(/\d{4}\.\d+\.\d+/)?.[0]||edition;
const fmt=(n,d=2)=>Number.isFinite(n)?Number(n.toFixed(d)).toString():'—';

function SourceLink({url,children,...props}){if(!/^https?:\/\//i.test(url||''))return null;return <a href={url} target="_blank" rel="noreferrer" {...props} onClick={e=>{if(window.blackwire){e.preventDefault();window.blackwire.openSource(url).catch(()=>{});}}}>{children||'Manufacturer source'}<ExternalLink size={12}/></a>;}
const familyLabel=f=>({'SBC':'All single-board computers','ESP32':'ESP32 & ESP8266','Other':'Other development boards','Raspberry Pi SBC':'Raspberry Pi computers','Other SBC':'Single-board computers','GPIO device':'Devices with GPIO','Expansion':'I/O & expansion boards','Source collection':'Manufacturer source collection'}[f]||f);
const shortType=t=>({'pinout image':'Pinout','GPIO reference image':'GPIO reference','board labeling image':'Board labels','original reference PDF':'Original PDF','source reference':'Source file','chip-package reference':'Chip package','pin function reference':'Pin functions'}[t]||t);
const initialWorkbench={favorites:[],measurements:[]};
function downloadJSON(data,name){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function App(){
 const [catalog,setCatalog]=useState(null),[loadError,setLoadError]=useState(''),[tab,setTab]=useState(()=>['devices','makers','wiring'].includes(new URLSearchParams(location.search).get('tab'))?new URLSearchParams(location.search).get('tab'):'library');
 const [query,setQuery]=useState(''),[brand,setBrand]=useState(''),[processor,setProcessor]=useState(''),[family,setFamily]=useState(''),[architecture,setArchitecture]=useState(''),[kind,setKind]=useState(''),[scope,setScope]=useState('all');
 const [globalPart,setGlobalPart]=useState(null),[globalGuide,setGlobalGuide]=useState(null);
 const [view,setView]=useState('grid'),[limit,setLimit]=useState(30),[selected,setSelected]=useState(null),[filters,setFilters]=useState(false),[sidebarOpen,setSidebarOpen]=useState(false);
 const [workbench,setWorkbench]=useState(initialWorkbench),[hydrated,setHydrated]=useState(false),[storageBlocked,setStorageBlocked]=useState(false),[toast,setToast]=useState(''),[powerSelection,setPowerSelection]=useState('');
 const searchRef=useRef(null);const deferredQuery=useDeferredValue(query);
 const notify=message=>setToast(message);
 useEffect(()=>{fetch(appAsset('catalog.json')).then(r=>{if(!r.ok)throw new Error('Catalog file could not be loaded.');return r.json();}).then(c=>{const featured=['raspberry-pi-rp2350-pico-2','pjrc-teensy-teensy-4-1','arduino-other-uno-r3'];c.boards=c.boards.map(b=>({...b,featured:featured.includes(b.id)||b.name==='ESP32-C5-DevKitC-1'||['T-Beam Supreme','T-Embed','T-Embed CC1101 Plus','T-LoRa Pager','Cardputer-Adv','Flipper Zero'].includes(b.name)}));setCatalog(c);if(webEdition){const boardId=new URLSearchParams(location.search).get('board');const requested=c.boards.find(b=>b.id===resolveBoardId(boardId,c.boardIdAliases));if(requested)setSelected(requested);}}).catch(e=>setLoadError(e.message));},[]);
 useEffect(()=>{(async()=>{try{const s=window.blackwire?await window.blackwire.loadState():JSON.parse(localStorage.getItem('blackwire-workbench')||'{}');setWorkbench(validateSavedWorkbench(s));}catch(e){setStorageBlocked(true);notify(webEdition?'Browser storage is unavailable. Open the guide full screen or export backups to keep your records.':e.message||'Saved workbench could not be read. Export a backup before making storage changes.');}finally{setHydrated(true);}})();},[]);
 useEffect(()=>{if(!hydrated||storageBlocked)return;const save=window.blackwire?window.blackwire.saveState(workbench):Promise.resolve().then(()=>localStorage.setItem('blackwire-workbench',JSON.stringify(workbench)));save.catch(()=>notify('Could not save your workbench. Export a backup to keep your changes.'));},[workbench,hydrated,storageBlocked]);
 useEffect(()=>{const handler=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus();}if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();searchRef.current?.focus();}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>setLimit(30),[query,brand,processor,family,architecture,kind,scope,tab]);
 useEffect(()=>{if(catalog&&hydrated&&!storageBlocked)setWorkbench(s=>remapWorkbench(s,catalog.boardIdAliases));},[catalog,hydrated,storageBlocked]);
 const favorites=workbench.favorites;
 const toggleFavorite=id=>setWorkbench(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]}));
 const available=useMemo(()=>catalog?.boards.filter(b=>b.assets.length)||[],[catalog]);
 const brands=useMemo(()=>[...new Set(available.map(b=>b.brand))].sort(),[catalog]);
 const processors=useMemo(()=>[...new Set(available.flatMap(b=>(b.processor||'').split(' / ')).filter(Boolean))].sort(),[catalog]);
 const families=useMemo(()=>[...new Set(available.map(b=>b.family))].sort(),[catalog]);
 const matches=useMemo(()=>['library','saved'].includes(tab)?searchBoards(catalog?.boards||[],{query:deferredQuery,brand,processor,family,architecture,kind,scope,savedOnly:tab==='saved',favorites}):[],[catalog,deferredQuery,brand,processor,family,architecture,kind,scope,tab,favorites]);
 const makerMatches=useMemo(()=>tab==='library'&&deferredQuery.trim()?searchMakerParts(catalog?.makerParts||[],{query:deferredQuery}):[],[catalog,deferredQuery,tab]);
 function clearFilters(){setQuery('');setBrand('');setProcessor('');setFamily('');setArchitecture('');setKind('');setScope('all');}
 function quickFilter(value){clearFilters();setTab('library');if(['CYD','SBC','FPGA','Expansion'].includes(value))setFamily(value);else setProcessor(value);}
 function navigate(value){setTab(value);setSidebarOpen(false);if(webEdition){const url=new URL(location.href);if(['devices','makers','wiring'].includes(value))url.searchParams.set('tab',value);else url.searchParams.delete('tab');if(value!=='makers')url.searchParams.delete('part');if(value!=='wiring')url.searchParams.delete('guide');history.replaceState(null,'',url);}}
 const activeFilters=[brand,processor,architecture,family&&familyLabel(family),kind&&shortType(kind),scope==='reviewed'?'Reviewed only':scope==='source'?'Source files only':''].filter(Boolean);
 if(loadError)return <div className="fatal"><BrandMark alt="Black Wire"/><h1>The reference library could not load.</h1><p>{loadError}</p><p>{webEdition?'Check your connection and reload the guide.':'Keep the library folder with the app, then reopen Black Wire.'}</p><button onClick={()=>location.reload()}>Try again</button></div>;
 if(!catalog)return <div className="loading-screen"><BrandMark alt="Black Wire"/><div className="loading-line"/><p>Opening your workbench…</p></div>;
 const sectionName=tab==='wiring'?'Wiring & protocols':tab==='power'?'Power desk':tab==='devices'?'Devices & IoT':tab==='makers'?'Displays & modules':tab==='about'?'About':tab==='saved'?'Saved boards':'Board library';
 return <div className="app-shell">
  <aside className={'sidebar '+(sidebarOpen?'is-open':'')}>
   <button className="brand-block" onClick={()=>{clearFilters();navigate('library');}} aria-label="Black Wire home"><span className="logo-tile"><BrandMark/></span><span className="wordmark">Black Wire<span>Maker's Technical Reference</span></span></button>
   {webEdition&&<SourceLink className="web-store-link" url="https://valleytechsolutions.tech">Visit the Valleytech store</SourceLink>}<div className="sidebar-section-label">Reference</div>
   <nav aria-label="Main navigation">
    <button className={tab==='library'?'active':''} onClick={()=>navigate('library')}><BookOpen size={19}/>Board library<span className="nav-count">{number(catalog.stats.boardsWithFiles)}</span></button>
    <button className={tab==='devices'?'active':''} onClick={()=>navigate('devices')}><Wifi size={19}/>Devices & IoT<span className="nav-count">{number(catalog.stats.devicesWithFiles||0)}</span></button>
    <button className={tab==='makers'?'active':''} onClick={()=>navigate('makers')}><Layers size={19}/>Displays & modules<span className="nav-count">{number(catalog.stats.makerRecords||0)}</span></button>
    <button className={tab==='wiring'?'active':''} onClick={()=>navigate('wiring')}><BookOpen size={19}/>Wiring & protocols<span className="nav-count">{number(catalog.wiringGuides?.length||0)}</span></button>
    <button className={tab==='power'?'active':''} onClick={()=>navigate('power')}><Zap size={19}/>Power desk<span className="new-dot"/></button>
    <button className={tab==='saved'?'active':''} onClick={()=>navigate('saved')}><Bookmark size={19}/>Saved boards<span className="nav-count">{favorites.length}</span></button>
   </nav>
   <div className="sidebar-section-label browse-label">Common filters</div>
   <nav className="quick-nav" aria-label="Quick processor filters">{['ESP32-C5','ESP32-S3','RP2040','RP2350','CYD','SBC','Expansion'].map(p=><button key={p} className={processor===p||family===p?'filter-active':''} onClick={()=>{quickFilter(p);setSidebarOpen(false);}}>{p==='CYD'?'CYD displays':p==='SBC'?'Single-board computers':p==='Expansion'?'I/O & expansion':p}</button>)}</nav>
   <SourceLink className="wiki-link" url="https://valleytech-black-wire-guide.pages.dev/wiki/"><BookOpen size={17}/>Reference wiki</SourceLink><div className="sidebar-bottom"><button className={'about-nav '+(tab==='about'?'active':'')} onClick={()=>navigate('about')}><Info size={17}/>About the guide</button><div className="sidebar-valleytech"><img src={appAsset('brand/valleytech.png')} alt="Valleytech Solutions logo"/><span>A VALLEYTECH<br/>SOLUTIONS PROJECT</span></div><div className="version"><span>App v{appVersion}</span><span>Collection {collectionId(catalog.edition)}</span></div></div>
  </aside>
  {sidebarOpen&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setSidebarOpen(false)}/>}
  <div className="main-shell">
   <header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setSidebarOpen(true)}><Menu size={21}/></button><span className="breadcrumb"><span className="guide-title">Black Wire</span><ChevronRight size={14} aria-hidden="true"/><b>{sectionName}</b></span><GlobalSearch catalog={catalog} query={query} setQuery={setQuery} inputRef={searchRef} openResult={({kind,record})=>{if(kind==='wiring'){navigate('wiring');setGlobalGuide(record);}else if(kind==='maker'){navigate('makers');setGlobalPart(record);}else{setSelected(record);}}}/><ThemeSwitch/></header>
   <main>
    {(tab==='library'||tab==='saved')&&<>
     <header className="page-header"><Kicker>{tab==='saved'?'Workbench':'Boards'}</Kicker><h1>{tab==='saved'?'Saved boards':'Board library'}</h1><p>{tab==='saved'?'Boards you have bookmarked on this device, with their references and review status.':`Pinouts, GPIO diagrams and manufacturer source files for ${number(catalog.stats.boardsWithFiles)} development boards and devices. Every reference records its source, board revision and review status.`}</p><dl className="page-meta"><div><dt>References</dt><dd>{number(catalog.stats.referenceEntries)}</dd></div><div><dt>Pinout images</dt><dd>{number(catalog.stats.physicalPinouts)}</dd></div><div><dt>Brands</dt><dd>{number(catalog.stats.brands)}</dd></div><div><dt>Collection</dt><dd>{collectionId(catalog.edition)}</dd></div><div><dt>Availability</dt><dd>{webEdition?'Browser':'Offline'}</dd></div></dl>{tab==='library'&&<div className="page-shortcuts"><span>Jump to</span>{['ESP32-C5','RP2040','RP2350','CYD','SBC','FPGA'].map(p=><button key={p} onClick={()=>quickFilter(p)}>{p==='CYD'?'CYD displays':p==='SBC'?'Single-board computers':p==='Expansion'?'I/O & expansion':p}</button>)}</div>}</header>
     <section className="catalog-section"><div className="section-heading"><div><h2>{tab==='saved'?'Saved boards':'Browse references'}</h2></div><button className="text-link" onClick={()=>{setQuery('');setTab('power');}}><Zap size={16}/>Power desk<ArrowUpRight size={16}/></button></div>
      <div className="filter-bar"><Select label="Manufacturer" value={brand} set={setBrand} options={brands} all="All manufacturers"/><Select label="Processor / microcontroller" value={processor} set={setProcessor} options={processors} all="All processors"/><Select label="Reference type" value={kind} set={setKind} options={['pinout image','GPIO reference image','board labeling image','original reference PDF','source reference','chip-package reference']} all="All reference types" display={shortType}/><button className={'filter-button '+(filters?'selected':'')} aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/>More filters{activeFilters.length>0&&<span>{activeFilters.length}</span>}</button></div>
      {filters&&<div className="extra-filters"><Select label="Board family" value={family} set={setFamily} options={['SBC',...families]} all="All families" display={familyLabel}/><Select label="Architecture" value={architecture} set={setArchitecture} options={[...new Set(available.map(b=>b.architecture).filter(Boolean))].sort()} all="All architectures"/><Select label="Review status" value={scope} set={setScope} options={['reviewed','source']} all="All saved references" allValue="all" display={v=>v==='reviewed'?'Reviewed references':'Original source files'}/><p>Source files include manuals, dimensions and diagrams awaiting review. Chip packages are labeled separately from boards.</p></div>}
      <p className="search-hint">Search by board, model number, brand or filename. Dashes, spaces and underscores work interchangeably; exact model matches appear first.</p><div className="result-toolbar"><span aria-live="polite"><b>{number(matches.length)}</b> {tab==='saved'?'saved ':''}board{matches.length===1?'':'s'} & devices{query&&<> matching <strong>“{query}”</strong></>}</span><div>{(query||activeFilters.length>0)&&<button className="clear-filters" onClick={clearFilters}>Clear filters<X size={13}/></button>}<div className="view-toggle" aria-label="Layout"><button aria-label="Grid view" aria-pressed={view==='grid'} className={view==='grid'?'selected':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button><button aria-label="List view" aria-pressed={view==='list'} className={view==='list'?'selected':''} onClick={()=>setView('list')}><List size={18}/></button></div></div></div>
      {tab==='library'&&(!query||makerMatches.length>0)&&<div className="maker-search-crosslink"><span>{query?`${number(makerMatches.length)} matching display & module records`:'New: displays, sensors, buttons and maker modules'}</span><button onClick={()=>navigate('makers')}>Explore parts<ArrowRight size={15}/></button></div>}
      {activeFilters.length>0&&<div className="active-filter-tags">{activeFilters.map(f=><span key={f}>{f}</span>)}</div>}
      {matches.length?<div className={'board-grid '+(view==='list'?'list-view':'')}>{matches.slice(0,limit).map(b=><BoardCard key={b.id} board={b} favorite={favorites.includes(b.id)} toggleFavorite={toggleFavorite} open={()=>setSelected(b)}/>)}</div>:<Empty icon={<Search size={30}/>} title={tab==='saved'&&!favorites.length?'Your workbench starts here.':'No matching references yet.'} text={tab==='saved'&&!favorites.length?'Save a board with the bookmark button to keep its references close.':'Try a shorter model name, remove a filter, or search by the manufacturer.'} action={<button className="primary-button" onClick={()=>{clearFilters();setTab('library');}}>Browse all boards<ArrowRight size={16}/></button>}/>}
      {matches.length>limit&&<div className="load-more"><button className="secondary-button" onClick={()=>setLimit(limit+30)}>Show 30 more<ChevronDown size={17}/></button><span>Showing {limit} of {number(matches.length)}</span></div>}
     </section>
    </>}
    {tab==='wiring'&&<WiringView catalog={catalog} query={deferredQuery} setQuery={setQuery} requestedGuide={globalGuide} onRequestedGuideHandled={()=>setGlobalGuide(null)} openPart={p=>{navigate('makers');setGlobalPart(p);}} SourceLink={SourceLink}/>}
    {tab==='makers'&&<MakersView requestedPart={globalPart} onRequestedPartHandled={()=>setGlobalPart(null)} catalog={catalog} query={deferredQuery} setQuery={setQuery} openBoard={setSelected} SourceLink={SourceLink}/>}
    {tab==='devices'&&<DevicesView catalog={catalog} query={deferredQuery} favorites={favorites} toggleFavorite={toggleFavorite} open={setSelected} BoardCard={BoardCard} SourceLink={SourceLink}/>}
    {tab==='power'&&<PowerDesk profiles={catalog.power} boards={catalog.boards} query={query} selectedId={powerSelection} setSelectedId={setPowerSelection} measurements={workbench.measurements} setMeasurements={next=>setWorkbench(s=>({...s,measurements:typeof next==='function'?next(s.measurements):next}))} openBoard={setSelected} notify={notify}/>}
    {tab==='about'&&<About catalog={catalog} workbench={workbench} setWorkbench={setWorkbench} notify={notify}/>}
    <footer className="main-footer colophon"><div className="colophon-brand"><BrandMark alt=""/><div><b>Black Wire Maker's Technical Reference Guide</b><span>Collection {collectionId(catalog.edition)} · App v{appVersion} · Every reference keeps its source, revision and review status.</span></div></div><div className="colophon-meta"><span>A Valleytech Solutions project</span><SourceLink url="https://www.youtube.com/@valleytechsolutions">@valleytechsolutions</SourceLink></div></footer>
   </main>
  </div>
  {selected&&<BoardDialog board={selected} profiles={catalog.power.filter(p=>p.boardIds.includes(selected.id))} favorite={favorites.includes(selected.id)} toggleFavorite={toggleFavorite} close={()=>setSelected(null)} onPower={id=>{setSelected(null);setPowerSelection(id);setQuery('');setTab('power');}} notify={notify}/>}
  {toast&&<div className="toast" role="status"><Info size={18}/><span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 </div>;
}
function Select({label,value,set,options,all,display=x=>x,allValue=''}){return <label className="select-field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}><option value={allValue}>{all}</option>{options.map(o=><option key={o} value={o}>{display(o)}</option>)}</select><ChevronDown size={14}/></label>;}
function BoardCard({board:b,favorite,toggleFavorite,open}){return <article className="board-card"><div className="board-image" onClick={open}><button className={'bookmark-button '+(favorite?'bookmarked':'')} onClick={e=>{e.stopPropagation();toggleFavorite(b.id);}} aria-label={(favorite?'Unsave ':'Save ')+b.name} aria-pressed={favorite}><Bookmark size={18} fill={favorite?'currentColor':'none'}/></button><button className="image-open" onClick={e=>{e.stopPropagation();open();}} aria-label={'View '+b.name+' references'}>{b.preview?<img loading="lazy" src={libraryURL(b.preview)} alt={b.name+' reference preview'}/>:<span className="no-preview"><FileText size={34}/><span>Reference sheets</span></span>}</button><span className={'image-badge '+(!b.pinouts?'subtle':'')}><span/>{b.pinouts?'PINOUT AVAILABLE':'REFERENCE FILES'}</span></div><div className="board-card-body"><div className="card-brand">{b.brand}</div>{b.lifecycle?.status==='pre-release'&&<span className="partial-label">Pre-release hardware</span>}<button className="card-title" onClick={open}>{b.name}<ArrowUpRight size={17}/></button><div className="card-description">{b.processor||familyLabel(b.family)}</div><div className="card-meta"><span><Layers size={13}/>{b.assets.length} reference{b.assets.length===1?'':'s'}</span>{b.partial?<span className="partial-label">Partial map</span>:b.scope==='source'?<span>Review pending</span>:<span className="reviewed-label"><Check size={12}/>Source recorded</span>}</div></div></article>;}
function Empty({icon,title,text,action}){return <div className="empty-state">{icon}<h3>{title}</h3><p>{text}</p>{action}</div>;}

function BoardDialog({board:input,profiles,favorite,toggleFavorite,close,onPower,notify}){
 const b={...input,assets:orderedAssets(input.assets)};
 const ref=useRef(null),stage=useRef(null),[assetId,setAssetId]=useState(b.assets[0]?.id),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[imageError,setImageError]=useState(false),[details,setDetails]=useState(false);
 const a=b.assets.find(a=>a.id===assetId)||b.assets[0];const raster=['png','jpg','jpeg','webp','gif','svg'].includes(a?.extension)&&!a?.previewError;
 useEffect(()=>{ref.current.showModal();const d=ref.current;const cancel=e=>{e.preventDefault();close();};d.addEventListener('cancel',cancel);return()=>d.removeEventListener('cancel',cancel);},[]);
 useEffect(()=>{setZoom(1);setRotation(0);setImageError(false);},[assetId]);
 const changeZoom=delta=>setZoom(v=>Math.max(.25,Math.min(6,v+delta)));
 async function save(){try{if(window.blackwire){await window.blackwire.saveAsset(a.file,b.name+' - '+a.label);}else{const link=document.createElement('a');link.href=libraryURL(a.file);link.download=b.name+' - '+a.label+'.'+a.extension;link.click();}}catch(e){notify(e.message);}}
 const drag=useRef(null);
 if(!a)return <dialog className="maker-dialog" ref={ref} aria-label={b.name+' references'} onCancel={e=>{e.preventDefault();close();}}><div className="maker-dialog-inner"><button className="icon-button" aria-label="Close board" onClick={close}><X size={22}/></button><h2>{b.name}</h2><HardwareLinks record={b} SourceLink={SourceLink}/><CoverageSummary record={b}/><p>This catalog entry is awaiting an exact hardware reference. No pin positions have been inferred.</p>{b.sources.map(url=><SourceLink key={url} url={url}>Recorded source</SourceLink>)}</div></dialog>;
 return <dialog className="board-dialog" ref={ref} aria-label={b.name+' references'}><div className="dialog-header"><div><span className="eyebrow">{b.brand} / {b.processor||familyLabel(b.family)}</span><h2>{b.name}</h2></div><div><button className={'secondary-button '+(favorite?'is-saved':'')} onClick={()=>toggleFavorite(b.id)}><Bookmark size={16} fill={favorite?'currentColor':'none'}/>{favorite?'Saved':'Save board'}</button>{webEdition&&<a className="secondary-button board-permalink" href={appAsset('index.html')+'?board='+encodeURIComponent(b.id)} target="_blank" rel="noreferrer">Board link<ExternalLink size={14}/></a>}<button className="icon-button close-dialog" aria-label="Close board" onClick={close}><X size={23}/></button></div></div>
  <div className="dialog-content"><aside className="asset-list"><div className="asset-list-heading">REFERENCE SHEETS <span>{b.assets.length}</span></div>{b.assets.map(asset=><button key={asset.id} className={'asset-item '+(asset.id===a.id?'active':'')} onClick={()=>setAssetId(asset.id)}>{asset.thumb?<img src={libraryURL(asset.thumb)} alt=""/>:<FileText size={27}/>}<span><b>{asset.label}</b><small>{shortType(asset.type)} · {asset.extension.toUpperCase()}</small></span></button>)}<div className="board-facts"><span className="eyebrow">HARDWARE RECORD</span><p><b>Revision</b>{b.revision||'Not identified'}</p><p><b>Coverage</b>{b.coverage}</p>{b.lifecycle&&<p className="development-label"><b>{b.lifecycle.status==='pre-release'?'Pre-release hardware':'Hardware availability'}</b>{b.lifecycle.note}</p>}{b.device?.note&&<p className="development-label"><b>Development status</b>{b.device.note}</p>}{profiles.length?<button className="power-shortcut" onClick={()=>onPower(profiles[0].id)}><Zap size={18}/><span>Power specifications<small>Sources & published tests</small></span><ChevronRight size={16}/></button>:<p className="muted"><Zap size={14}/> Power specifications not yet researched for this exact board.</p>}</div></aside>
   <section className="viewer">{b.lifecycle&&<p className="hardware-lifecycle"><b>{b.lifecycle.status==='pre-release'?'Pre-release hardware. ':'Hardware availability. '}</b>{b.lifecycle.note}</p>}<HardwareLinks compact record={b} SourceLink={SourceLink} onOpenDocument={file=>{const match=b.assets.find(a=>a.file===file);if(match)setAssetId(match.id);}}/><CoverageSummary record={b}/>{b.pinReferences?.length>0&&<details className="board-pin-details"><summary>Pin names & purpose</summary><PinReference record={b} SourceLink={SourceLink}/></details>}<div className="viewer-toolbar"><span><ImageIcon size={16}/>{shortType(a.type)}{a.partial&&<span className="chip-warning">PARTIAL</span>}</span><div>{(raster||a.extension==='pdf')&&<><button className="icon-button" aria-label="Zoom out" onClick={()=>changeZoom(-.25)}><Minus size={17}/></button><span className="zoom-value">{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" onClick={()=>changeZoom(.25)}><Plus size={17}/></button><button className="icon-button" aria-label="Fit image" onClick={()=>{setZoom(1);setRotation(0);}}><Maximize2 size={17}/></button><button className="icon-button" aria-label="Rotate image" onClick={()=>setRotation(v=>(v+90)%360)}><RotateCw size={17}/></button><i/> </>}<button className="download-button" onClick={save}><Download size={16}/>Save original</button></div></div>
    <div className={'image-stage'+(a.extension==='pdf'?' is-pdf':' ')} ref={stage} onPointerDown={e=>{if(!raster||e.pointerType!=='mouse'||e.button!==0)return;e.preventDefault();drag.current={x:e.clientX,y:e.clientY,left:stage.current.scrollLeft,top:stage.current.scrollTop};stage.current.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current){stage.current.scrollLeft=drag.current.left-(e.clientX-drag.current.x);stage.current.scrollTop=drag.current.top-(e.clientY-drag.current.y);}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
     {raster&&!imageError?<ReferenceImage key={a.id} src={libraryURL(a.display||a.file)} alt={b.name+' — '+a.label} zoom={zoom} rotation={rotation} onError={()=>setImageError(true)}/>:a.extension==='pdf'?<React.Suspense fallback={<p>Opening PDF viewer…</p>}><PdfViewer key={a.id} url={libraryURL(a.file)} label={a.label} zoom={zoom} rotation={rotation}/></React.Suspense>:<Empty icon={<FileText size={36}/>} title={a.previewError?'This source image needs replacement.':imageError?'This source image could not be decoded.':'Original reference file'} text={a.previewError?'The retained manufacturer file could not be fully decoded. Use another reference or consult the linked source.':imageError?'The original file is retained. Download it to inspect or replace the source.':'Save this file and open it with a compatible viewer.'} action={<button className="secondary-button" onClick={save}><Download size={16}/>Save file</button>}/>}
    </div><div className="viewer-caption"><span>{a.width&&a.height?`${number(a.width)} × ${number(a.height)} · `:''}{fmt(a.bytes/1024)} KB{a.display?' · Screen preview; original resolution retained':''}</span><span>{raster?'Drag to pan · Zoom for pin labels':'Original document'}</span></div>
    <div className="source-panel"><div><span className={'source-status '+(a.review==='Unreviewed source'?'unreviewed':'')}><ShieldCheck size={15}/>{a.review}</span><button className="text-link" aria-expanded={details} onClick={()=>setDetails(!details)}>Source & revision details<ChevronDown size={14}/></button></div>{a.notes&&<p>{a.notes}</p>}{a.type==='chip-package reference'&&<p>This depicts an IC package, not a development-board pinout.</p>}{details&&<div className="source-details"><p><b>Image revision:</b> {a.revision||'Not identified'}</p><p><b>Source credit:</b> {a.rights}</p><div className="source-links">{[...new Set([a.url,...a.sources])].filter(Boolean).map((url,i)=><SourceLink key={url} url={url}>{i===0?'Original source file':'Source documentation '+i}</SourceLink>)}{a.vector&&<a href={libraryURL(a.vector)} download onClick={e=>{if(window.blackwire){e.preventDefault();window.blackwire.saveAsset(a.vector,b.name+' - vector reference').catch(e=>notify(e.message));}}}>Original vector<Download size={12}/></a>}</div><p><b>Original collection paths:</b></p>{(a.originals||[]).map(p=><code key={p}>{p}</code>)}<p className="hash">SHA-256: {a.hash}</p><p>Source images are preserved. Pin assignments have not been independently electrically verified.</p></div>}</div>
   </section></div></dialog>;
}

function PowerDesk({profiles,boards,query,selectedId,setSelectedId,measurements,setMeasurements,openBoard,notify}){
 const [section,setSection]=useState('chart'),[testForm,setTestForm]=useState(false);
 const matching=profiles.filter(p=>normalize(p.name+' '+p.brand+' '+p.logic).includes(normalize(query)));
 const selected=profiles.find(p=>p.id===selectedId);
 return <div className="power-page"><div className="power-hero"><Kicker>Power</Kicker><h1>Power desk</h1><p>Board supply ratings with manufacturer citations, published current measurements, and calculators for adapters, batteries and power budgets.</p><div className="power-hero-note"><FlaskConical size={23}/><div><b>{profiles.length} sourced board profiles · {profiles.reduce((s,p)=>s+p.observations.length,0)} published observations</b><span>Supply capacity and current consumption are different. Each result keeps its source and conditions.</span></div></div></div>
  <PowerBasics SourceLink={SourceLink}/><div className="desk-tabs" role="tablist" aria-label="Power tools">{[['chart','Voltage chart',Zap],['adapter','Adapter check',Settings2],['battery','Battery math',Battery],['budget','Power budget',Calculator],['tests','My measurements',FlaskConical]].map(([id,name,Icon])=><button key={id} role="tab" aria-selected={section===id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon size={17}/>{name}{id==='tests'&&measurements.length>0&&<span>{measurements.length}</span>}</button>)}</div>
  {section==='chart'&&<section className="power-chart"><div className="section-heading"><div><h2>Voltage & current reference</h2><p className="muted">Board-specific inputs. Original manufacturer sources.</p></div><span className="tag-outline">{matching.length} profiles</span></div><div className="chart-table-wrap"><table className="power-table"><thead><tr><th>BOARD / INPUT</th><th>VOLTAGE</th><th>SUPPLY CAPACITY</th><th>PUBLISHED RESULTS</th><th/></tr></thead><tbody>{matching.map(p=><React.Fragment key={p.id}><tr className={selectedId===p.id?'expanded':''} onClick={()=>setSelectedId(selectedId===p.id?'':p.id)}><td><button className="table-board-name" onClick={e=>{e.stopPropagation();setSelectedId(selectedId===p.id?'':p.id);}} aria-expanded={selectedId===p.id}>{p.name}</button><span>{p.input}</span></td><td><b className="mono">{p.voltageMin!=null?`${p.voltageMin}–${p.voltageMax} V`:p.nominal?`${p.nominal} V nominal`:'Not recorded'}</b><span>{p.rangeKind}</span></td><td><b className="mono">{p.supplyCurrentA?`${p.supplyCurrentA} A recommended`:'Not specified here'}</b><span>{p.supplyCurrentA?'Adapter capacity, not consumption':'Verify for your workload'}</span></td><td>{p.observations.length?<span className="measurement-badge"><FlaskConical size={13}/>{p.observations.length} operating result{p.observations.length===1?'':'s'}</span>:<span className="muted">No result collected</span>}</td><td><ChevronDown size={17}/></td></tr>{selectedId===p.id&&<tr><td colSpan="5" className="profile-cell"><PowerProfile profile={p} onBoard={()=>{const b=boards.find(b=>p.boardIds.includes(b.id)&&b.assets.length);if(b)openBoard(b);else notify('This board is tracked, but no exact board image is collected yet.');}}/></td></tr>}</React.Fragment>)}</tbody></table></div>{!matching.length&&<Empty icon={<Search size={30}/>} title="No power profile matches yet." text="This chart contains only sourced specifications. A missing profile does not mean a board has no pinout in the library."/>}<div className="inline-note"><Info size={17}/><p>Input power, logic voltage and GPIO output limits are not interchangeable. A blank current rating means it has not been established here. Published results describe one setup; they do not certify an adapter or another board revision.</p></div></section>}
  {section==='adapter'&&<AdapterTool profiles={profiles} selected={selected} SourceLink={SourceLink}/>}
  {section==='battery'&&<BatteryTool/>}
  {section==='budget'&&<BudgetTool/>}
  {section==='tests'&&<section className="measurements-section"><div className="section-heading"><div><h2>Your measured results</h2><p className="muted">Stored on this device. Your observations stay separate from manufacturer data.</p></div><button className="primary-button" onClick={()=>setTestForm(true)}><Plus size={17}/>Record a measurement</button></div>{measurements.length?<div className="measurement-list">{measurements.map(m=><article key={m.id}><div className="measurement-record-heading"><span className="eyebrow">YOUR BENCH / {m.date}</span><button className="icon-button" aria-label={'Delete measurement '+m.id} onClick={()=>setMeasurements(s=>s.filter(x=>x.id!==m.id))}><Trash2 size={15}/></button></div><h3>{boards.find(b=>b.id===m.boardId)?.name||m.boardId}</h3><div className="reading"><strong>{fmt(m.voltage)}<small>V</small></strong><strong>{fmt(m.currentMa)}<small>mA average</small></strong><strong>{fmt(m.voltage*m.currentMa/1000,3)}<small>W calculated</small></strong></div><p>{m.condition}</p><dl><dt>Revision</dt><dd>{m.revision}</dd><dt>Input</dt><dd>{m.input}</dd><dt>Instrument</dt><dd>{m.instrument}</dd>{m.peakMa!=null&&<><dt>Peak</dt><dd>{m.peakMa} mA</dd></>}</dl>{m.notes&&<p className="muted">{m.notes}</p>}</article>)}</div>:<Empty icon={<FlaskConical size={32}/>} title="Put a number to your next build." text="Record measured voltage, current, board revision and workload. Published measurements are already available in the voltage chart." action={<button className="secondary-button" onClick={()=>setTestForm(true)}>Add your first result<Plus size={16}/></button>}/>}
  </section>}
  {testForm&&<MeasurementForm boards={boards} close={()=>setTestForm(false)} save={m=>{setMeasurements(s=>[m,...s]);setTestForm(false);notify('Measurement saved to your local workbench.');}}/>}
 </div>;
}
function PowerProfile({profile:p,onBoard}){return <div className="power-profile"><div className="profile-facts"><div><span className="eyebrow">EXACT HARDWARE</span><h3>{p.name}</h3><p>{p.revision}</p><button className="text-link" onClick={onBoard}>Find board references<ArrowUpRight size={14}/></button></div><div><span className="eyebrow">LOGIC / CONNECTOR</span><p><b>{p.logic}</b></p><p>{p.connector}</p></div><div><span className="eyebrow">CURRENT RATING</span><p>{p.currentMeaning}</p></div></div><p className="profile-note">{p.notes}</p><p className="footnote">{p.reviewStatus||'Source recorded; not independently electrically tested.'}</p>{p.observations.length>0&&<><h4>Published operating results <span>Not tested by Black Wire</span></h4><div className="observations-wrap"><table className="observations"><thead><tr><th>TYPE / CONDITIONS</th><th>INPUT</th><th>CURRENT</th><th>POWER¹</th></tr></thead><tbody>{p.observations.map((o,i)=><tr key={i}><td><span className="observation-kind">{o.kind}</span><p>{o.condition}</p><small>{o.caveat}</small><SourceLink url={p.sources[o.source]?.url}>Source {o.source+1}: {p.sources[o.source]?.title}</SourceLink></td><td className="mono">{o.voltage?o.voltage+' V':'Not stated'}</td><td className="mono">{o.currentMa} mA{o.peakMa!=null&&<small>Reported peak: {o.peakMa} mA</small>}</td><td className="mono">{o.voltage?fmt(o.voltage*o.currentMa/1000,4)+' W':'—'}</td></tr>)}</tbody></table></div><p className="footnote">¹ Calculated from the published voltage × current, when both are provided. These are scenario results, not guaranteed limits.</p></>}<div className="profile-sources">{p.sources.map((s,i)=><div key={i}><SourceLink url={s.url}>{s.title}</SourceLink><span>{s.section} · checked {s.checked}</span>{s.file&&<a href={libraryURL(s.file)} download onClick={e=>{if(window.blackwire){e.preventDefault();window.blackwire.saveAsset(s.file,p.name+' - power source').catch(e=>console.error(e));}}}>Save original PDF<Download size={12}/></a>}</div>)}</div></div>;}

const num=v=>String(v).trim()===''?NaN:Number(v);

function MeasurementForm({boards,close,save}){
 const ref=useRef(null);const [m,setM]=useState({boardId:'',revision:'',input:'',date:new Date().toISOString().slice(0,10),voltage:'',currentMa:'',peakMa:'',condition:'',instrument:'',notes:''}),[error,setError]=useState('');
 useEffect(()=>{ref.current.showModal();},[]);
 const set=(k,v)=>setM({...m,[k]:v});
 function submit(e){e.preventDefault();const form=e.currentTarget.form||e.currentTarget;if(!form.reportValidity())return;const record={...m,id:crypto.randomUUID(),voltage:num(m.voltage),currentMa:num(m.currentMa),peakMa:m.peakMa===''?null:num(m.peakMa)};const err=validateMeasurement(record,new Set(boards.map(b=>b.id)));if(err)setError(err);else save(record);}
 return <dialog className="measurement-dialog" ref={ref} onCancel={e=>{e.preventDefault();close();}} aria-label="Record a measurement"><form onSubmit={e=>e.preventDefault()} onKeyDown={e=>{if(e.key==='Enter'&&e.target.tagName==='INPUT')submit(e);}}><div className="dialog-header"><div><span className="eyebrow">YOUR BENCH NOTES</span><h2>Record a measurement</h2></div><button type="button" className="icon-button" aria-label="Close measurement form" onClick={close}><X size={22}/></button></div><div className="measurement-form-body"><label className="form-label">Board<select aria-label="Board" required value={m.boardId} onChange={e=>set('boardId',e.target.value)}><option value="">Select the exact board</option>{boards.filter(b=>b.assets.length).sort((a,b)=>a.name.localeCompare(b.name)).map(b=><option key={b.id} value={b.id}>{b.brand} — {b.name}</option>)}</select></label><div className="field-grid"><label className="form-label">PCB revision<input required value={m.revision} onChange={e=>set('revision',e.target.value)} placeholder="Printed board revision"/></label><label className="form-label">Power input point<input required value={m.input} onChange={e=>set('input',e.target.value)} placeholder="e.g. VSYS + GND"/></label><NumericField label="Measured voltage" value={m.voltage} set={v=>set('voltage',v)} unit="V"/><NumericField label="Average current" value={m.currentMa} set={v=>set('currentMa',v)} unit="mA"/><NumericField label="Measured peak (optional)" value={m.peakMa} set={v=>set('peakMa',v)} unit="mA"/><label className="form-label">Date<input type="date" required value={m.date} onChange={e=>set('date',e.target.value)}/></label></div><label className="form-label">Conditions / firmware / peripherals<textarea required value={m.condition} onChange={e=>set('condition',e.target.value)} placeholder="What was running? Radio activity, connected peripherals, clock speed, temperature…"/></label><label className="form-label">Instrument / measurement method<input required value={m.instrument} onChange={e=>set('instrument',e.target.value)} placeholder="Meter model and measurement setup"/></label><label className="form-label">Additional notes<textarea value={m.notes} onChange={e=>set('notes',e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<p className="muted">This saves a user observation, not a certified operating limit.</p></div><div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button type="button" className="primary-button" onClick={submit}><Check size={16}/>Save measurement</button></div></form></dialog>;
}
function About({catalog,workbench,setWorkbench,notify}){
 const input=useRef(null);
 async function exportData(){const data={format:'black-wire-backup',version:1,exportedAt:new Date().toISOString(),...workbench};try{if(window.blackwire)await window.blackwire.exportBackup(JSON.stringify(data,null,2));else downloadJSON(data,'Black-Wire-workbench.json');}catch(e){notify(e.message);}}
 async function importData(e){try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw new Error('Backup is larger than 5 MB.');const data=validateBackup(remapWorkbench(JSON.parse(await file.text()),catalog.boardIdAliases),new Set(catalog.boards.map(b=>b.id)));setWorkbench(s=>({...s,favorites:[...new Set([...s.favorites,...data.favorites])],measurements:[...new Map([...s.measurements,...data.measurements].map(m=>[m.id,m])).values()]}));notify('Backup merged with your existing workbench.');}catch(e){notify(e.message);}finally{e.target.value='';}}
 return <div className="about-page"><div className="about-brand"><Kicker>Colophon</Kicker><h1>About Black Wire</h1><p>A reference collection of development-board pinouts and manufacturer source files. Each image records its source, board revision and review status; pin assignments are never inferred.</p></div><div className="about-cards"><section><BookOpen size={24}/><h2>{webEdition?"Your reference library, online.":"Your library, offline."}</h2><p>{number(catalog.stats.referenceEntries)} searchable reference entries, including {number(catalog.stats.physicalPinouts)} physical pinout source images. Original manufacturer/source files are included with clear review labels.</p><p>Board revisions, source credits and partial diagrams stay attached to their images. This collection is growing; it does not claim every board ever made.</p><span className="tag-outline">{catalog.edition}</span></section><section><Download size={24}/><h2>Keep your workbench.</h2><p>{webEdition?'Bookmarks and measurements stay in this browser. Export a backup to keep a copy or move your records to the desktop app. Clearing browser storage can erase local records.':'Bookmarks and your measurements are stored on this device. Export a backup to move them between Windows, Linux and macOS.'}</p><div className="backup-actions"><button className="primary-button" onClick={exportData}><Download size={16}/>Export backup</button><button className="secondary-button" onClick={()=>input.current.click()}><Upload size={16}/>Import backup</button><input ref={input} type="file" accept="application/json,.json" hidden onChange={importData}/></div><p className="muted">Import merges records. {webEdition?'An internet connection is required to load references; your backup contains personal records, not the image library.':'The image library is shipped separately from your personal backup.'}</p></section></div><section className="about-valleytech"><img src={appAsset('brand/valleytech.png')} alt="Valleytech official logo"/><div><span className="eyebrow">ROOTED IN VALLEYTECH</span><h2>Maintained by Valleytech Solutions</h2><p>The Valleytech Technical Reference Guide collection is the foundation of Black Wire. Board diagrams retain their original creators’ credit and source records. The app does not claim ownership of manufacturer artwork.</p><p className="muted">First Edition / 2026 · App v{appVersion} · No accounts, analytics or cloud sync.</p></div></section><LicenseNotices/></div>;
}
class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={error:null};}static getDerivedStateFromError(error){return {error};}render(){return this.state.error?<div className="fatal"><h1>Something interrupted the workbench.</h1><p>Your original library files have not changed.</p><pre>{this.state.error.message}</pre><button onClick={()=>location.reload()}>Reopen Black Wire</button></div>:this.props.children;}}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
