import React,{useState} from 'react';
import {Info,Battery,Plus,Trash2} from 'lucide-react';
import {adapterCheck,batteryEstimate,budgetTotal} from './domain.mjs';

const num=v=>String(v).trim()===''?NaN:Number(v);
const fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumSignificantDigits:5}).format(n):'—';
export function NumericField({label,value,set,unit,min=0,step='any',hint,readOnly=false}){
 return <label className="numeric-field"><span>{label}</span><div><input type="number" value={value} min={min} step={step} readOnly={readOnly} onChange={e=>set(e.target.value)} aria-label={label}/>{unit&&<b>{unit}</b>}</div>{hint&&<small>{hint}</small>}</label>;
}
export function PowerBasics({SourceLink}){
 return <details className="power-basics"><summary>Before you connect: voltage, current and battery essentials</summary><div className="power-basics-grid">
  <section><h3>Match the power input</h3><p>USB, VIN, VSYS, battery and GPIO pins have different limits. Use the exact connector's operating range, polarity and board revision. Absolute maximum is a damage boundary, not a design target.</p><SourceLink url="https://store.arduino.cc/products/arduino-uno-rev3">Arduino input and regulator guidance</SourceLink></section>
  <section><h3>Capacity is not consumption</h3><p>1 A = 1,000 mA. Adapter amperage is available capacity; an idle measurement is one workload. Include peripherals and startup or radio peaks. A charger's total wattage does not establish its current at the voltage your board needs.</p><SourceLink url="https://www.raspberrypi.com/documentation/computers/getting-started.html#power-supply">Raspberry Pi supply and cable guidance</SourceLink></section>
  <section><h3>Check every connected supply</h3><p>Some boards require USB power to be isolated from an external input. Others provide a power-path circuit. Follow the exact board instructions before connecting USB, a battery and external power together.</p><SourceLink url="https://www.pjrc.com/teensy/external_power.html">PJRC external power</SourceLink><SourceLink url="https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c5/esp32-c5-devkitc-1/user_guide.html#power-supply-options">Espressif supply options</SourceLink></section>
  <section><h3>Battery math is not a pack approval</h3><p>Use the cell's chemistry-specific full-charge and discharge limits. Match the charger, protection, series count, current and temperature limits. A nominal voltage or runtime estimate cannot establish a suitable charger or safe cell assembly.</p><SourceLink url="https://learn.adafruit.com/li-ion-and-lipoly-batteries/protection-circuitry">Adafruit battery protection guidance</SourceLink></section>
 </div></details>;
}
const emptyChecks=()=>({regulated:false,connectorConfirmed:false,polarityConfirmed:false,powerPathConfirmed:false,limitsConfirmed:false,loadConfirmed:false});
export function AdapterTool({profiles,selected,SourceLink}){
 const [profileId,setProfileId]=useState(selected?.id||''),[v,setV]=useState(''),[a,setA]=useState(''),[currentUnit,setCurrentUnit]=useState('A');
 const [vmin,setVmin]=useState(selected?.voltageMin??''),[vmax,setVmax]=useState(selected?.voltageMax??''),[load,setLoad]=useState(selected?.supplyCurrentA??''),[type,setType]=useState('');
 const [checks,setChecks]=useState(emptyChecks);
 const p=profiles.find(p=>p.id===profileId);
 const edit=set=>value=>{set(value);setChecks(emptyChecks());};
 const result=adapterCheck({voltage:num(v),current:num(a)/(currentUnit==='mA'?1000:1),minVoltage:num(vmin),maxVoltage:num(vmax),loadCurrent:num(load),outputType:type,...checks,profile:p});
 function pick(id){const next=profiles.find(p=>p.id===id);setProfileId(id);setVmin(next?.voltageMin??'');setVmax(next?.voltageMax??'');setLoad(next?.supplyCurrentA??'');setChecks(emptyChecks());}
 const confirmations=[['limitsConfirmed','I checked the documented operating range for this exact input and revision.'],['loadConfirmed','The current requirement includes peripherals and startup/transmit peaks.'],['regulated','I confirmed regulated DC output, including voltage under load.'],['connectorConfirmed','The connector, selected input pin and USB-PD voltage/current mode match.'],['polarityConfirmed','The positive and negative contacts match the exact board documentation.'],['powerPathConfirmed','All connected USB, battery and external supplies follow the board power-path instructions.']];
 return <section className="tool-layout"><div className="tool-form"><div className="eyebrow">THE WALL-WART DRAWER</div><h2>Compare adapter ratings.</h2><p className="muted">Use the adapter OUTPUT label and the exact board input. Confirmations reset when ratings change.</p>
  <label className="form-label">Board power profile<select aria-label="Board power profile" value={profileId} onChange={e=>pick(e.target.value)}><option value="">Enter my own board ratings</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} — {p.input}</option>)}</select></label>
  {p&&<div className="small-callout power-input-notes"><b>{p.input}</b><span>{p.revision}</span><span>{p.connector}</span><span>GPIO / logic: {p.logic}</span><p>{p.notes}</p>{p.voltageMin==null?<p>No operating tolerance is recorded. A nominal value alone cannot establish the allowed range.</p>:<p>{p.rangeKind}. Sourced bounds are locked for this profile.</p>}{p.sources.slice(0,1).map(s=><SourceLink key={s.url} url={s.url}>{s.title}</SourceLink>)}</div>}
  <h3>Adapter output</h3><div className="field-grid"><NumericField label="Output voltage" value={v} set={edit(setV)} unit="V"/><NumericField label="Rated output current" value={a} set={edit(setA)} unit={currentUnit}/></div>
  <label className="form-label">Adapter current unit<select aria-label="Adapter current unit" value={currentUnit} onChange={e=>{setCurrentUnit(e.target.value);setA('');setChecks(emptyChecks());}}><option>A</option><option>mA</option></select><small>Changing the unit clears the current entry. 500 mA = 0.5 A.</small></label>
  <label className="form-label">Output type<select aria-label="Output type" value={type} onChange={e=>edit(setType)(e.target.value)}><option value="">Check the output label</option><option>DC</option><option>AC</option></select></label>
  <h3>Board input / complete load</h3><div className="field-grid"><NumericField label="Minimum allowed voltage" value={vmin} set={edit(setVmin)} unit="V" readOnly={p?.voltageMin!=null}/><NumericField label="Maximum allowed voltage" value={vmax} set={edit(setVmax)} unit="V" readOnly={p?.voltageMax!=null}/></div>
  <NumericField label="Required capacity or worst-case load" value={load} set={edit(setLoad)} unit="A" hint="Use amperes: 100 mA = 0.1 A. Include attached hardware and peaks; typical idle current is not a supply rating."/>
  <fieldset className="power-confirmations"><legend>Check this combination</legend>{confirmations.map(([key,label])=><label className="checkbox-label" key={key}><input type="checkbox" checked={checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/>{label}</label>)}</fieldset>
 </div><div className={'tool-result result-'+result.level} role="status" aria-live="polite"><span className="eyebrow">RATING COMPARISON · NOT A HARDWARE TEST</span><Info size={36}/><h2>{result.title}</h2>{result.watts!=null&&<div className="large-number">{fmt(result.watts)}<span>W rated output at the entered voltage</span></div>}<ul>{result.messages.map(m=><li key={m}>{m}</li>)}</ul>{result.headroom!=null&&<p className="result-detail">Current capacity above entered load: <b>{fmt(result.headroom)} A</b></p>}<div className="tool-tip"><b>The voltage must still be right.</b><p>More available current does not force that current into a load. It cannot compensate for the wrong voltage, polarity, connector or power path. A label comparison does not verify regulation, transient response, wiring or thermal limits.</p></div></div></section>;
}
export function BatteryTool(){
 const [s,setS]=useState(''),[p,setP]=useState(''),[v,setV]=useState(''),[full,setFull]=useState(''),[ah,setAh]=useState(''),[w,setW]=useState(''),[eff,setEff]=useState(''),[usable,setUsable]=useState(''),[low,setLow]=useState('');
 const r=batteryEstimate({series:num(s),parallel:num(p),cellVoltage:num(v),cellFullVoltage:num(full),cellAh:num(ah),loadWatts:num(w),efficiency:num(eff),usablePercent:num(usable),minCellVoltage:low===''?null:num(low)});
 return <section className="tool-layout"><div className="tool-form"><div className="eyebrow">SERIES, PARALLEL & RUNTIME</div><h2>Estimate energy and runtime.</h2><p className="muted">Enter your cell datasheet values and measured load. No battery chemistry or cell ratings are assumed.</p><div className="field-grid"><NumericField label="Cells in series" value={s} set={setS} min={1} step={1} unit="S"/><NumericField label="Parallel strings" value={p} set={setP} min={1} step={1} unit="P"/><NumericField label="Cell nominal voltage" value={v} set={setV} unit="V"/><NumericField label="Cell fully charged voltage" value={full} set={setFull} unit="V"/><NumericField label="Cell capacity" value={ah} set={setAh} unit="Ah" hint="2,500 mAh = 2.5 Ah. Use the rating for one cell."/><NumericField label="Total load power" value={w} set={setW} unit="W"/><NumericField label="Conversion efficiency" value={eff} set={setEff} unit="%" hint="Use the combined efficiency of all conversion stages."/><NumericField label="Usable nominal energy" value={usable} set={setUsable} unit="%" hint="Account for reserve, cutoff, ageing and temperature. 100% means no capacity derating."/></div><NumericField label="Minimum cell voltage under load" value={low} set={setLow} unit="V" hint="Optional: use the design's documented cutoff to estimate low-voltage pack current."/><div className="inline-note"><Info size={17}/><p>Compare full-charge and minimum pack voltage with the converter input range. Check cell discharge limits, charger chemistry/series count, protection and temperature separately.</p></div></div><div className="tool-result" role="status"><span className="eyebrow">NOMINAL-ENERGY ESTIMATE</span><Battery size={35}/>{r?<><h2>{s}S{p}P / {r.cells} cells</h2><div className="large-number">{fmt(r.wh)}<span>Wh nominal energy</span></div><dl className="result-grid"><dt>Nominal / full charge</dt><dd>{fmt(r.nominal)} / {fmt(r.full)} V</dd><dt>Pack capacity</dt><dd>{fmt(r.ah)} Ah</dd><dt>Runtime with entered derating</dt><dd>{fmt(r.hours)} hours</dd><dt>Pack current at nominal voltage</dt><dd>{fmt(r.inputAmps)} A</dd><dt>Pack current at minimum voltage</dt><dd>{r.lowInputAmps==null?'Cutoff not entered':`${fmt(r.lowInputAmps)} A at ${fmt(r.lowVoltage)} V`}</dd></dl><div className="tool-tip"><b>Not a guaranteed runtime or discharge rating.</b><p>Assumes constant load, matching cells and the efficiency/usable-energy factors entered. Current rises as voltage falls for a constant-power load. Peaks and unequal sharing between cells require separate analysis.</p></div></>:<p>Enter positive ratings, whole numbers of cells, and efficiency/usable energy above 0% and at most 100%. Full-charge voltage must be at least nominal; minimum voltage cannot exceed nominal.</p>}</div></section>;
}
export function BudgetTool(){
 const blank=()=>({id:crypto.randomUUID(),label:'',voltage:'',current:'',quantity:'1',efficiency:''});
 const [rows,setRows]=useState(()=>[blank()]),[margin,setMargin]=useState(''),[supply,setSupply]=useState('');
 const r=budgetTotal(rows.map(row=>({...row,voltage:num(row.voltage),current:num(row.current),quantity:num(row.quantity),efficiency:num(row.efficiency)})),num(margin));
 const amps=r&&num(supply)>0?r.withMargin/num(supply):NaN;
 const set=(id,key,value)=>setRows(rows.map(r=>r.id===id?{...r,[key]:value}:r));
 return <section className="budget-section"><div className="section-heading"><div><div className="eyebrow">MULTI-BOARD PROJECTS</div><h2>Build a power budget.</h2><p className="muted">Enter each final load once. Currents are amperes at that row's rail voltage.</p></div><button className="secondary-button" onClick={()=>setRows([...rows,blank()])}><Plus size={16}/>Add load</button></div><div className="budget-rows">{rows.map((row,i)=><div className="budget-row" key={row.id}><label className="form-label">Load name<input value={row.label} aria-label={'Load name '+(i+1)} onChange={e=>set(row.id,'label',e.target.value)}/></label><NumericField label={'Rail voltage '+(i+1)} value={row.voltage} set={v=>set(row.id,'voltage',v)} unit="V"/><NumericField label={'Load current '+(i+1)} value={row.current} set={v=>set(row.id,'current',v)} unit="A"/><NumericField label={'Quantity '+(i+1)} value={row.quantity} set={v=>set(row.id,'quantity',v)} min={1} step={1}/><NumericField label={'Efficiency '+(i+1)} value={row.efficiency} set={v=>set(row.id,'efficiency',v)} unit="%"/><button className="icon-button" disabled={rows.length===1} aria-label={'Remove load '+(i+1)} onClick={()=>setRows(rows.filter(r=>r.id!==row.id))}><Trash2 size={16}/></button></div>)}</div><div className="budget-bottom"><div className="field-grid"><NumericField label="Planning margin" value={margin} set={setMargin} unit="%" hint="0–500%; a planning allowance, not an electrical limit."/><NumericField label="Minimum upstream supply voltage" value={supply} set={setSupply} unit="V" hint="Use the lowest expected supply voltage for this current estimate."/></div><div className="budget-totals" role="status">{r?<><div><span>At the loads</span><strong>{fmt(r.loadWatts)} W</strong></div><div><span>With conversion losses</span><strong>{fmt(r.inputWatts)} W</strong></div><div className="highlight"><span>With planning margin</span><strong>{fmt(r.withMargin)} W</strong><small>{Number.isFinite(amps)&&amps>0?`${fmt(amps)} A at ${supply} V`:'Enter a valid minimum supply voltage'}</small></div></>:<p>Enter every load rating, quantity, efficiency and planning margin to calculate.</p>}</div></div><div className="inline-note"><Info size={17}/><p>Do not add a regulator output and its downstream loads twice. Efficiency is the combined upstream-to-load conversion path; use 100% only when modeling no conversion loss. Include quiescent loads, startup and radio peaks. Total watts do not establish each regulator's current, cable, connector, fuse or thermal suitability.</p></div></section>;
}
