import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Cable,Download,Minus,Plus,Maximize2} from 'lucide-react';
import {Kicker} from './Theme.jsx';
import {libraryURL,webEdition} from './runtime.mjs';
import {searchWiringGuides} from './wiring-guides.mjs';
import './wiring.css';
import useReferenceNavigation from './useReferenceNavigation.js';

export default function WiringView({catalog,query,setQuery,requestedGuide,onRequestedGuideHandled,openPart,SourceLink}){
 const guides=catalog.wiringGuides||[];
 const [category,setCategory]=useState(''),[selected,setSelected]=useState(()=>guides.find(g=>g.id===new URLSearchParams(location.search).get('guide'))||null);
 const heading=useRef(null);
 const matches=useMemo(()=>searchWiringGuides(guides,query,category),[guides,query,category]);
 function pick(g){setSelected(g);if(webEdition){const u=new URL(location.href);u.searchParams.set('tab','wiring');u.searchParams.delete('board');u.searchParams.delete('part');if(g)u.searchParams.set('guide',g.id);else u.searchParams.delete('guide');history.replaceState(null,'',u);}}
 useEffect(()=>{if(requestedGuide){pick(requestedGuide);onRequestedGuideHandled();}},[requestedGuide]);
 useEffect(()=>{if(selected)heading.current?.focus();},[selected]);
 if(selected)return <article className="wiring-detail" aria-label="Wiring guide"><button className="text-link" onClick={()=>pick(null)}><ArrowLeft size={17}/>All wiring guides</button><header className="page-header"><Kicker>{selected.category}</Kicker><h1 tabIndex={-1} ref={heading}>{selected.name}</h1><p>{selected.summary}</p><div className="wiring-scope"><b>Applies to</b><p>{selected.scope}</p></div></header><div className="wiring-purpose"><section><h2>When to use it</h2><p>{selected.useWhen}</p></section><section><h2>Why it works this way</h2><p>{selected.why}</p></section></div><WiringDiagram key={selected.id} guide={selected}/><section className="wiring-section"><h2>Connection reference</h2><div className="wiring-table" tabIndex={0} aria-label="Connection table; scroll horizontally on small screens"><table><thead><tr>{selected.columns.map(c=><th key={c} scope="col">{c}</th>)}</tr></thead><tbody>{selected.rows.map((r,i)=><tr key={i}>{r.map((v,j)=>j===0?<th key={j} scope="row">{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div></section><div className="wiring-purpose"><section><h2>Make the connection</h2><ol>{selected.steps.map(s=><li key={s}>{s}</li>)}</ol></section><section className="wiring-checks"><h2>Check before powering</h2><ul>{selected.checks.map(s=><li key={s}>{s}</li>)}</ul></section></div>{selected.relatedParts.length>0&&<section className="wiring-section"><h2>Matching module references</h2><p>Open the exact module's original images, connector view and datasheets.</p><div className="wiring-related">{selected.relatedParts.map(id=>catalog.makerParts.find(p=>p.id===id)).filter(Boolean).map(p=><button className="secondary-button" key={p.id} onClick={()=>openPart(p)}>{p.name}<ArrowUpRight size={16}/></button>)}</div></section>}<section className="wiring-section"><h2>Sources & review</h2><p>{selected.review}. Reviewed {selected.revision}.</p>{selected.sources.map(s=><div className="wiring-source" key={s.url}><SourceLink url={s.url}>{s.title}</SourceLink><span>{s.locator} · checked {s.checked}</span></div>)}<details><summary>Credit, license & diagram fingerprint</summary><p>{selected.rights}</p><SourceLink url="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0</SourceLink><code>SHA-256 {selected.image.hash}</code></details></section><section className="wiring-section"><h2>Continue learning</h2><div className="wiring-related">{selected.relatedGuides.map(id=>guides.find(g=>g.id===id)).filter(Boolean).map(g=><button className="secondary-button" key={g.id} onClick={()=>pick(g)}>{g.name}<ArrowUpRight size={16}/></button>)}</div>{webEdition&&<a className="text-link" href={'?tab=wiring&guide='+selected.id}>Link to this guide</a>}</section></article>;
 return <div className="wiring-page"><header className="page-header"><Kicker>Connections</Kicker><h1>Wiring & protocols</h1><p>Know what connects, when to use it and why. Original connection diagrams, signal tables and practical checks for your next prototype.</p><dl className="page-meta"><div><dt>Guides</dt><dd>{guides.length}</dd></div><div><dt>Diagrams</dt><dd>{guides.length}</dd></div><div><dt>Collection</dt><dd>First Edition / 2026</dd></div></dl></header><div className="wiring-intro"><Cable size={26}/><p>Start with the exact interface and hardware. Connector shape and wire color alone do not establish voltage or pin function. Each guide states its scope and keeps its manufacturer sources.</p></div><section aria-label="Browse wiring guides"><div className="wiring-filters"><label>Category<select aria-label="Wiring category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All wiring guides</option>{[...new Set(guides.map(g=>g.category))].map(c=><option key={c}>{c}</option>)}</select></label><button className="text-link" onClick={()=>{setCategory('');setQuery('');}}>Clear search & filters</button></div><p role="status">{matches.length} matching wiring guides{query&&<> for “{query}”</>}</p><div className="wiring-grid">{matches.map(g=><button key={g.id} className="wiring-card" aria-label={'Open wiring guide '+g.name} onClick={()=>pick(g)}><img src={libraryURL(g.image.file)} alt="" loading="lazy"/><span className="wiring-card-body"><small>{g.category}</small><strong>{g.name}<ArrowUpRight size={17}/></strong><span>{g.summary}</span><em>Original connection diagram · source linked</em></span></button>)}</div>{!matches.length&&<p className="empty-state">No matching guide yet. Try CAN, RJ45, I2C, JTAG or NFC, or clear the category filter.</p>}</section></div>;
}

function WiringDiagram({guide:g}){
 const [zoom,setZoom]=useState(1),[error,setError]=useState(''),stage=useRef(null);
 useReferenceNavigation(stage,zoom,setZoom,{resetKey:g.id});
 async function save(){try{if(window.blackwire)await window.blackwire.saveAsset(g.image.file,g.name);else{const a=document.createElement('a');a.href=libraryURL(g.image.file);a.download=g.id+'.svg';a.click();}}catch{setError('Could not save this diagram. Try opening the guide full screen.');}}
 return <figure className="wiring-diagram"><div className="wiring-tools"><b>Connection diagram</b><div><button className="icon-button" aria-label="Zoom wiring diagram out" disabled={zoom<=.25} onClick={()=>setZoom(v=>Math.max(.25,v-.25))}><Minus size={18}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom wiring diagram in" disabled={zoom>=6} onClick={()=>setZoom(v=>Math.min(6,v+.25))}><Plus size={18}/></button><button className="icon-button" aria-label="Fit wiring diagram" onClick={()=>setZoom(1)}><Maximize2 size={18}/></button><button className="secondary-button" onClick={save}><Download size={17}/>Save diagram</button></div></div><p className="zoom-hint">Pinch or Ctrl+scroll to zoom · Drag to pan · Double-click or double-tap to zoom</p><div ref={stage} className="wiring-stage" tabIndex={0} aria-label="Wiring diagram; scroll to pan when zoomed"><img data-zoom-content draggable="false" src={libraryURL(g.image.file)} alt={g.image.alt} style={{width:zoom*100+'%',maxWidth:'none'}} onError={()=>setError('The diagram could not load. Reload or consult the source links below.')}/></div><figcaption>Original Black Wire connection diagram · {g.review}</figcaption>{error&&<p role="alert">{error}</p>}</figure>;
}
